config/routes.rb
Recipes::Application.routes.draw do
  root "pages#home"
  resources :users
  resources :sessions
  resources :ingredients
  resources :fridges
  resources :recipes

  get "/logout" => "sessions#destroy", as: "logout"
  patch "/fridges" => "fridges#update"
  patch "/recipes" => "recipes#update"
  post "/recipes/search" => "recipes#search"
end

app/models/fridge.rb
class Fridge < ActiveRecord::Base
	belongs_to :user
	belongs_to :ingredient
end

app/controllers/fridges_controller.rb
class FridgesController < ApplicationController
    before_action :require_login
    before_action :identify_user

    def identify_user
      user = User.find_by(id: session[:user_id])
      if user
        @username = user.name
      end
    end

    def require_login
      if session[:user_id].blank?
        redirect_to new_session_path, notice: "Please login to create and edit your inventory"
      end
    end

    def index
        @user = User.find(session[:user_id])
    	@frs = User.find(@user.id).ingredients
    end

    def new
    	cats = Ingredient.uniq.pluck('category')
    	@gr = Hash.new
    	cats.each do |cat|
    		@gr[cat] = Ingredient.where(["category='"+cat+"'"])
    	end
    end

    def show
    	@fridge = User.find(session[:user_id]).ingredients
    end

    def edit
        #cats = Ingredient.uniq.pluck('category')
        @fridge = User.find(session[:user_id]).ingredients
        @everythingelse = Ingredient.all.order('name asc') - @fridge
    end

    def create
    	x = params[:ingredgients_checkbox]
    	x.each do |ingredient_id|
		    m = Fridge.new
		    m.user_id = session["user_id"]
		    m.ingredient_id = ingredient_id
		    m.save
		end
	    redirect_to user_path(session["user_id"])
    end

    def update(toadd={},todelete={})
        todelete = params[:delete_checkbox] if not params[:delete_checkbox].nil?
        toadd = params[:add_checkbox] if not params[:add_checkbox].nil?
        u = User.find(session["user_id"])
        
        if todelete
            todelete.each do |t|
                u.ingredients.destroy(t)
            end
        end

        if toadd #ruby hates looping over nil?
            toadd.each do |t|
                Fridge.create(:user_id => u.id, :ingredient_id => t)
            end
        end

        redirect_to user_path(session["user_id"]), notice: "deleted #{todelete.count} & added #{toadd.count} ingredients to your inventory"
    end


end

app/helpers/fridges_helper.rb
module FridgesHelper
end

app/views/fridges/edit.html.erb
<div class='well bs-component'>
<legend><h1>Edit your Inventory</h1></legend>

<%= form_tag "/fridges", :method => 'patch' do %>
	<div class="row">
      <div class="form-group">
        <div class="col-lg-10">
          <%= submit_tag "Submit", class: "btn btn-primary" %>
          <!-- <button type="submit" class="btn btn-primary" >Submit Changes</button> -->
        </div>
      </div>
    </div>
	<h2>Remove items from your inventory</h2>

	<% @fridge.each do |g| %>
				<div class="row">
				  <div class="col-lg-2">
				    <div class="input-group">
				    	<%= check_box_tag  "delete_checkbox[]",g.id %>
						<%= label_tag(g.id, g.name ) %>
				    </div><!-- /input-group -->
				  </div><!-- /.col-lg-6 -->
				</div><!-- /.row -->
	<% end %>

	<hr>
	<h2>Add items to your inventory</h2>
	<% chunks = @everythingelse.each_slice(@everythingelse.count / 4).to_a %>
	<div class="row">
	<% chunks.each do |chunk|%>
					
					  <div class="col-sm-3">	
		<% chunk.each do |g| %>

					    <div class="input-group">
					    	<%= check_box_tag  "add_checkbox[]",g.id %>
							<%= label_tag(g.id, g.name ) %>
					    </div><!-- /input-group -->

		<% end %>
							  </div><!-- /.col-lg-6 -->
	<% end %>

	<div class="row">
      <div class="form-group">
        <div class="col-lg-10">
          <%= submit_tag "Submit", class: "btn btn-primary" %>
          <!-- <button type="submit" class="btn btn-primary" >Submit Changes</button> -->
        </div>
      </div>
    </div>

<% end %>

</div>

app/views/fridges/index.html.erb
<h1 class="page-header">Your Ingredients</h1>

<h2></h2>
<% @frs.each do |ingr| %>
  <div class="row">
    <div class="col-md-3">
      <%= link_to ingr.name , ingredient_path(ingr.id)%>
    </div>
  </div>

<% end %>

app/views/fridges/new.html.erb
<div class='well bs-component'>
<h1>What do you have in your fridge?</h1>
<%= form_tag "/fridges" do %>
	<div class="row">
      <div class="form-group">
        <div class="col-lg-10">
          <%= submit_tag "Add Ingredients", class: "btn btn-primary" %>
          <!-- <button type="submit" class="btn btn-primary" >Submit Changes</button> -->
        </div>
      </div>
    </div>
	<% @gr.each do |cat,ingrs| %>

		<h3><p><%= cat %></p></h3>
			<ul class='list-inline'>
			<% ingrs.each do |g| %>  
				   	<li>
				    	<%= check_box_tag  "ingredgients_checkbox[]",g.id %>
						<%= label_tag(g.id, g.name ) %>
					</li>
	  		<% end %>
	  		</ul>
		<hr>
	<% end %>
	<div class="row">
      <div class="form-group">
        <div class="col-lg-10">
          <%= submit_tag "Add Ingredients", class: "btn btn-primary" %>
          <!-- <button type="submit" class="btn btn-primary" >Submit Changes</button> -->
        </div>
      </div>
    </div>
<% end %>
</div>

app/views/fridges/show.html.erb
<h2>Here's what you have available:</h2>

<% @fridge.each do |ingr| %>
<div class="container">
	<div class="col-md-3">
		<h4><%= link_to ingr.name, ingredient_path(ingr.id) %></h4>
	</div>
</div>
<% end %>