config/routes.rb
Recipes::Application.routes.draw do
  root "pages#home"
  resources :users
  resources :sessions
  resources :ingredients
  resources :fridges
  resources :recipes

  get "/logout" => "sessions#destroy", as: "logout"
  patch "/fridges" => "fridges#update"
  patch "/recipes" => "recipes#update"
  post "/recipes/search" => "recipes#search"
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :ingredients, :through => :fridges
	has_many :fridges
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :require_login, :except => [:new, :create]
  before_action :identify_user

  def identify_user
    user = User.find_by(id: session[:user_id])
    if user
      @username = user.name
    end
  end

  def require_login
    if session[:user_id].blank?
      redirect_to root_url, notice: "Please login to access that page"
    end
  end
  
  def show
    @user = User.find(session[:user_id])
    @fr = Fridge.find_by(:user_id => @user.id)
    @ingredients = @user.ingredients
  end

  def create
    user = User.new
    user.name = params[:name]
    user.email = params[:email]
    user.password = params[:password]
    user.password_confirmation = params[:password]

    if User.find_by(email: user.email)
      redirect_to :back, notice: "Account already exists for this email"
    else
      user.save!
      session[:user_id] = user.id
      redirect_to root_url
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class='well bs-component'>

<%= form_tag "/users", :class=>'form-horizontal', :id=> 'recipeform' do %>
  <fieldset>
    <legend><h1>Sign Up</h1></legend>

    <div class="form-group">
      <label for="Name" class="col-lg-2 control-label">Name</label>
      <div class="col-lg-5">
        <%= text_field_tag :name, nil, class: "form-control", required: "" %>
      </div>
    </div>


    <div class="form-group">
      <label for="Email" class="col-lg-2 control-label">Email</label>
      <div class="col-lg-5">
        <%= text_field_tag :email, nil, class: "form-control", required: "" %>
      </div>
    </div>

    <div class="form-group">
      <label for="Password" class="col-lg-2 control-label">Password</label>
      <div class="col-lg-5">
        <%= password_field_tag :password, nil, class: "form-control", required: "" %>
      </div>
    </div>

      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <%= submit_tag "Sign Up", class: "btn btn-primary"  %>
        </div>
      </div>

  </fieldset>
<% end %>

</div>

app/views/users/show.html.erb
<div class='well bs-component'>


	<div class="col-lg-10">
		<%= link_to "Create a new Recipe", "/recipes/new"%>
	</div>
	<div class="col-lg-10">
		<%= link_to "Create a new Ingredient", "/ingredients/new"%>
	</div>

	<% if @fr != nil %>

    <div class="row">
   	<label class="control-label col-lg-10"></label>
      <div class="col-lg-7">
			<%= link_to "Edit the items in your inventory", edit_fridge_path %>
	  </div>
	</div>

    <div class="row">
   	<label class="control-label col-lg-10"></label>
      <div class="col-lg-7">
			<%= link_to "View the items in your inventory", fridge_path %>
	  </div>
	</div>


	<br>

	<fieldset>
	<%= form_tag "/recipes/search" do %>
		<div class="row">
      <div class="form-group">
        <div class="col-lg-10">
          <%= submit_tag "What can I make?", class: "btn btn-primary" %>
          <!-- <button type="submit" class="btn btn-primary" >Submit Changes</button> -->
        </div>
      </div>
    </div>
				<div hidden>
				
				<% @ingredients.each do |g| %>  
					<%= check_box_tag  "ingredgients_checkbox[]",g.name, checked="true" %><%= g.name %>
		  		<% end %>
		  		</div>
	<% end %>
	</fieldset>

	<% else %>

    <div class="row">
   	<label class="control-label col-lg-10"></label>
      <div class="col-lg-7">
			You haven't selected any ingredients yet.  To do a custom search <%= link_to "add some items to your inventory!", new_fridge_path %>
	  </div>
	</div>

	<% end %>

</div>


</div>