config/routes.rb
Recipes::Application.routes.draw do
  root "pages#home"
  resources :users
  resources :sessions
  resources :ingredients
  resources :fridges
  resources :recipes

  get "/logout" => "sessions#destroy", as: "logout"
  patch "/fridges" => "fridges#update"
  patch "/recipes" => "recipes#update"
  post "/recipes/search" => "recipes#search"
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	has_many :users, :through => :fridges
	has_many :fridges
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    before_action :require_login, :except => [:index, :show]
    before_action :identify_user

    def identify_user
      user = User.find_by(id: session[:user_id])
      if user
        @username = user.name
      end
    end

    def require_login
      if session[:user_id].blank?
        redirect_to new_session_path, notice: "Please login to create and edit ingredients"
      end
    end



    def index
    	#@ingrs = Ingredient.all.order("name asc")
    	
    	cats = Ingredient.uniq.pluck('category')
    	@gr = Hash.new
    	cats.each do |cat|
            if cat.length > 0
    		  @gr[cat] = Ingredient.where(["category='"+cat+"'"]).order("name asc")
            end
    	end
        puts @gr
    end

  	def show
    	@ingredient = Ingredient.find(params[:id])
	end

    def edit
        @ingredient = Ingredient.find(params[:id])        
    end

    def update
        i = Ingredient.find(params[:id])
        ingr.name = params[:name]
        ingr.category = params[:category]
        ingr.save!
        redirect_to ingredient_path(ingr.id)
    end


	def create
	    ingr = Ingredient.new
	    ingr.name = params[:name]
	    ingr.category = params[:category]
	    ingr.save!
	    redirect_to ingredient_path(ingr.id)
  	end

end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/edit.html.erb
<div class='well bs-component'>
<%= form_tag "/ingredients/#{@ingredient.id}", :class=>'form-horizontal', :id=> 'recipeform', :method => 'patch' do %>
  <fieldset>
    <legend><h1>Edit the Ingredient</h1></legend>


    <div class="form-group">
      <label for="Name" class="col-lg-2 control-label">Name</label>
      <div class="col-lg-5">
        <%= text_field_tag :name, nil, class: "form-control", required: "" , value: @ingredient.name %>
      </div>
    </div>

    <div class="form-group">
      <label for="ext_url" class="col-lg-2 control-label">Category</label>
      <div class="col-lg-5">
        <!-- <input type="text" class="form-control" id="ext_url" placeholder="http://some.site.com/apple_pie"> -->
        <%= text_field_tag :category, nil, class: "form-control", value: @ingredient.category%>
      </div>
    </div>


      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <%= submit_tag "Submit Changes", class: "btn btn-primary", id: @ingredient.id %>
          <!-- <button type="submit" class="btn btn-primary" >Submit Changes</button> -->
        </div>
      </div>

  </fieldset>
<% end %>

</div>

app/views/ingredients/index.html.erb
<div class='well bs-component'>

<h1 class="page-header">Ingredients <%= @username %></h1>


<div class="row">
	<div class="col-lg-10">
		<label> <%= link_to "Create a new Ingredient", "/ingredients/new"%> or Select a few and search for a recipe </label>
	</div>
</div>

<fieldset>

<%= form_tag "/recipes/search" do %>

	<div class="row">
      <div class="form-group">
        <div class="col-lg-10">
			<%= submit_tag "Submit", class: "btn btn-primary" %>
		</div>
	  </div>
	</div>

	<% @gr.sort.each do |cat,ingrs| %>

		<h3><p><%= cat %></p></h3>
			<ul class='list-inline'>
			<% ingrs.each do |g| %>  
				    	<li><%= check_box_tag  "ingredgients_checkbox[]",g.name %><%= g.name %></li>
	  		<% end %>
	  		</ul>
		<hr>
	<% end %>
	<div class="row">
      <div class="form-group">
        <div class="col-lg-10">
			<%= submit_tag "Submit", class: "btn btn-primary" %>
		</div>
	  </div>
	</div>
<% end %>
</fieldset>
</div>

</row>



</div>

app/views/ingredients/new.html.erb
<div class='well bs-component'>
<%= form_tag "/ingredients", :class=>'form-horizontal' do %>
  <fieldset>
    <legend><h1>Add an ingredient</h1></legend>

    <div class="form-group">
      <label for="Name" class="col-lg-2 control-label">Name</label>
      <div class="col-lg-5">
        <%= text_field_tag :name, nil, class: "form-control", required: "" %>
      </div>
    </div>

    <div class="form-group">
      <label for="Name" class="col-lg-2 control-label">Category</label>
      <div class="col-lg-5">
        <%= text_field_tag :category, nil, class: "form-control", required: "" %>
      </div>
    </div>

      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <%= submit_tag "Create", class: "btn btn-primary"  %>
        </div>
      </div>

  </fieldset>
<% end %>

</div>

app/views/ingredients/show.html.erb
<div class='well bs-component'>
<h1>Ingredient</h1>

<p>Name: <%= @ingredient.name %></p>
<p>Category: <%= @ingredient.category %></p>
 <%= link_to "Edit", edit_ingredient_path %>

</div>