config/routes.rb
Recipes::Application.routes.draw do
  root "pages#home"
  resources :users
  resources :sessions
  resources :ingredients
  resources :fridges
  resources :recipes

  get "/logout" => "sessions#destroy", as: "logout"
  patch "/fridges" => "fridges#update"
  patch "/recipes" => "recipes#update"
  post "/recipes/search" => "recipes#search"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Ugly Recipe</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/amelia/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>


  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Ugly Recipe", root_url, :class => "navbar-brand" , :style => 'background: black'%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Recipes", recipes_url %></li>
        <li><%= link_to "Ingredients", ingredients_url %></li>
        <% if session[:user_id].blank? %>
          <li><%= link_to "Sign Up", new_user_url %></li>
          <li><%= link_to "Sign In", new_session_url %></li>
        <% else %>
          <li><%= link_to "Fridge", user_url(session[:user_id]) %></li>
          <li><%= link_to "Sign Out", logout_url %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>